/**
 * HospitalRun
 * +HospitalRun API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface User { 
    firstName?: string;
    lastName?: string;
    id: string;
}
