name: GitHub CI

on:
  push:
    branches:
      - "!master"
  pull_request:
    branches:
      - master

jobs:
  npm:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - run: git config --global core.autocrlf false # this is needed to prevent git changing EOL after cloning on Windows OS
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install with npm
        run: |
          npm install
      - name: Build
        run: |
          npm run build
